var subtotal = (13 + 1) * 5;
var shipping = 0.5 * (13 +1);
var total = sudtotal + shipping;
var elSud = document.getElementById(elementld: 'subtotal');
elSud.textContent = subtotal;
var elShip = document.getElementById(elementld: 'shipping');
elShip.textContent = shipping;
var elTotal = document.getElementById(elementld: 'total');
elTotal.textContent = total;